/** DO NOT EDIT THIS FILE - it is auto-generated by the i18n-plus script from .yaml files */
/** Generated on 2021-08-20T22:38:43.158Z */
export const LocaleKeys = {
	simple: {
		raw: "simple.raw",
		oneVar: "simple.oneVar",
		twoVars: "simple.twoVars",
		oneVarWithRaw: "simple.oneVarWithRaw",
		threeVarsWithRaw: "simple.threeVarsWithRaw",
	},
	advanced: {
		conjugateOne: "advanced.conjugateOne",
		conjugateOneAndInterpolate: "advanced.conjugateOneAndInterpolate",
		conjugateTwo: "advanced.conjugateTwo",
		conjugateTwoAndInterpolate: "advanced.conjugateTwoAndInterpolate",
	},
};

export default LocaleKeys;
